apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-dns-manager-be
  labels:
    app: cloudflare-dns-manager-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-dns-manager-be
  template:
    metadata:
      labels:
        app: cloudflare-dns-manager-be
    spec:
      containers:
      - name: cloudflare-dns-manager-be
        image: jsrankit/cloudflare-dns-manager-backend:100525-07-19  # This will be updated by GitHub Actions
        ports:
        - containerPort: 3001
