apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-dns-manager
  labels:
    app: cloudflare-dns-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudflare-dns-manager
  template:
    metadata:
      labels:
        app: cloudflare-dns-manager
    spec:
      containers:
      - name: cloudflare-dns-manager
        image: jsrankit/cloudflare-dns-manager:latest  # This will be updated by GitHub Actions
        ports:
        - containerPort: 8080