apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-dns-manager-fe
  labels:
    app: cloudflare-dns-manager-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-dns-manager-fe
  template:
    metadata:
      labels:
        app: cloudflare-dns-manager-fe
    spec:
      containers:
      - name: cloudflare-dns-manager-fe
        image: jsrankit/cloudflare-dns-manager-frontend:120525-09-53  # This will be updated by GitHub Actions
        ports:
        - containerPort: 8080
